### PR TITLE
luci-app-music-remote-center: Chang dependencies

### PR DESCRIPTION
**Pull request by 1582130940**
* forked-daapd -> owntone

If owntone's renaming is applied upstream, merge this change.

### CODE REVIEW

**Comment by Beginner-Go** [comment]
还有这边的 `init.d` `config` 文件会和 package 那边的冲突吗？

**Comment by 1582130940** [comment]
> 还有这边的 `init.d` `config` 文件会和 package 那边的冲突吗？

package那边init只有start和stop啊，如果冲突的话讲道理没改名之前就冲突了，因为package那边也只是改名

**Comment by Beginner-Go** [comment]
好吧 那您改下0755

**Comment by 1582130940** [comment]
> 好吧 那您改下0755

麻烦您看下是否还是644？

**Comment by Beginner-Go** [comment]
似乎还好0664 忘记 'git add . ' 了？

**Comment by 1582130940** [comment]
> 似乎还是0664 忘记 `git add .` 了？

**Comment by 1582130940** [comment]
> 似乎还是0664 忘记 `git add .` 了？

Please review

[pull 2b223ff] luci-app-music-remote-center: Chang dependencies
 Author: zxlhhyccc <zxlhhy@gmail.com>
 Date: Sat Nov 12 13:21:33 2022 +0800
 10 files changed, 48 insertions(+), 48 deletions(-)
 delete mode 100644 applications/luci-app-music-remote-center/luasrc/controller/forked-daapd.lua
 create mode 100644 applications/luci-app-music-remote-center/luasrc/controller/owntone.lua
 rename applications/luci-app-music-remote-center/luasrc/model/cbi/{forked-daapd.lua => owntone.lua} (84%)
 rename applications/luci-app-music-remote-center/luasrc/view/{forked-daapd/forked-daapd_status.htm => owntone/owntone_status.htm} (79%)
 rename applications/luci-app-music-remote-center/po/zh-cn/{forked-daapd.po => owntone.po} (100%)
 rename applications/luci-app-music-remote-center/root/etc/config/{forked-daapd => owntone} (84%)
 rename applications/luci-app-music-remote-center/root/etc/init.d/{forked-daapd => owntone} (60%)
 delete mode 100755 applications/luci-app-music-remote-center/root/etc/uci-defaults/luci-forked-daapd
 create mode 100755 applications/luci-app-music-remote-center/root/etc/uci-defaults/luci-owntone

**Review by Beginner-Go — APPROVED** [review]

**Pull request merged**
